<?php

use Drupal\uchi_pro\Form\SettingsForm;
use Drupal\uchi_pro\Service\ImportCoursesService;

function uchi_pro_cron() {

  $settings = Drupal::config(SettingsForm::SETTINGS);

  $useCron = $settings->get('use_cron');
  if ($useCron) {
    try {
      $importCoursesService = new ImportCoursesService();
      $importCoursesService->importCourses();
    } catch (Exception $e) {
      watchdog_exception('error', $e);
    }
  }
}

function uchi_pro_get_url() {
  $settings = Drupal::config(SettingsForm::SETTINGS);
  return $settings->get('url');
}

function uchi_pro_get_access_token() {
  $settings = Drupal::config(SettingsForm::SETTINGS);
  return $settings->get('access_token');
}
